language: scala
script: "sbt +clean +coverage +test +publish"
before_script:
- mkdir -p test-dbs/postgres
- sudo chown postgres:postgres test-dbs/postgres/
after_success: "sbt coveralls"
services:
  - mysql
  - postgresql
